### ISSUE TITLE
Multinomial model is not cooperative

### ISSUE THREAD

**Issue by RHainez** [mcfanda/gamlj#22]
Hi, 

I try to use the Multinomial model following the example you provide here https://mcfanda.github.io/gamlj_docs/gzlm_example1.html#simple_multinomial_model but I can't slide "prog" in "Dependant variable" because the module expects a continuous variable (ruler symbol) and "prog" is a nominal variable (Venn diagram).
Could you please tell me how you managed to get it done in your screen capture (I use the lastest versions of jamovi and GAMLj) ?

And thank you very much for your work :)

**Comment by mcfanda** [comment]
Hi, did you select "multinomial model" above the variables?

**Comment by mcfanda** [comment]
It is strange, however, because there is no ruler (or other little icons) in the dependent variable field in the GZLM. Which version of GAMLj do you have?
thanks for helping out with the debug :-)

**Comment by RHainez** [comment]
Hi,

Yes, I selected Multinomial model, I tried relaunch, reboot, reinstall :) I installed Jamovi 0.8.1.7 and GAMLj from the store today.

**Comment by mcfanda** [comment]
Hi, it must be version mismatch. I'm asking the core team to check the
version in the jamovi library. In the meantime you can check out the
developer version on github that does not have this bug

Il 17 nov 2017 6:47 PM, "RHainez" <notifications@github.com> ha scritto:

**Comment by mcfanda** [comment]
Hi
please check out version 0.9.2 in jamovi library. It should work as expected

**Comment by RHainez** [comment]
Hi,
I just updated GAMLj and it works perfectly, thank you very much!

**Comment by mcfanda** [comment]
thank you, please let me know any improvement you can think of
