### ISSUE TITLE
marginal means

### ISSUE THREAD

**Issue by wmmurrah** [mcfanda/gamlj#28]
I love this package. I am trying to compare the output to SPSS and R base and car ANOVA. All looks good, except for the marginal means in both the general and generalized linear models. For a factorial ANOVA the estimated means for the cells have the correct numbers, but the labeling is incorrect (means are indicated for the incorrect cells). I have compared the results for two separate data set to both SPSS and R with the `emmeans` package.
The estimated cell means also do not match with the Effects Plot.

**Comment by mcfanda** [comment]
Hi William,
I'll check it out right away
thanks

**Comment by mcfanda** [comment]
Hi William, thanks a lot for spotting the bug. The EMM interaction  table was ordered in the wrong way. I pushed version 0.9.5 that fixes the problem. In a few days it will be also in jamovi library
