### ISSUE TITLE
Combine variables

### ISSUE THREAD

**Issue by acescos** [mcfanda/gamlj#37]
Firstly, I want to congratulate you for having developed the excellent module for the jamovi software.

Secondly, I want to ask you to include in the GAMLj module an option to combine variables. In R, the function is given by the cbind command.
combined.vars = cbind (dataframe$var1, dataframe$var2)
It works in the same way as the POOL command that is used by syntax in SPSS.

Third, until the above can be developed, please, show me if there is an option in the module in its current version to combine variables.

Best regards,
Alejandro

**Comment by mcfanda** [comment]
thanks. 
The option you mentioned regards the data management rather than the GAMLj module per se. You may want to redirect the question to jamovi core developers. You can use github (https://github.com/jamovi/jamovi) or the jamovi forum (https://forum.jamovi.org/)
