### ISSUE TITLE
Error in running scripts generated by Jamovi on R 

### ISSUE THREAD

**Issue by ssyoon** [mcfanda/gamlj#38]
First of all, thank you for the great package. 
I found that this package is tremendously useful, but I found a problem when I tried to run the script generated on Jamovi directly on R. 
I am wondering if GAMLj is only running on Jamovi or there is a way to use GAMLj on R directly. 
If there is a way to use GAMLj on R directly, can you provide more detailed instruction? 
Thank you.

**Comment by mcfanda** [comment]
Hi, thanks for the feedback
I'm working on the R interface and soon it should be all set. In the meantime, you can already use gamlj in R by specifying the `modelterms` in the R syntax:

``

gamlj::gamljMixed(
    data = data,
    dep = "y",
    factors = "wfac",
    covs = "x",
    cluster = "cluster",
    randomTerms = list(
        c("Intercept", "cluster")),
    modelTerms = list(
        "wfac",
        "x"),
    contrasts = list(
        list(
            var="wfac",
            type="deviation")),
    scaling = list(
        list(
            var="x",
            type="centered")))
``

**Comment by amiroquai** [comment]
I would like to add my gratitude for the package! It is exactly what I need. Nevertheless, I am not able to run the syntax at all in R. I get the error message that the package is not available. where can I find the gamlj package for R?
Many thanks from Switzerland

**Comment by mcfanda** [comment]
HI, you need to install gamlj from R, you can run this:
``
devtools::install_github('mcfanda/gamlj')
``
Please notice the current version ogf gamlj (0.9.8) is still buggy when ran in R. We are working on version 1.0.0 which will solve all the R interface problems

**Comment by amiroquai** [comment]
Sweet! Thanks!
