### ISSUE TITLE
Issue with scaling

### ISSUE THREAD

**Issue by dropmann** [mcfanda/gamlj#39]
So in the files glm.events.js, gzlm.events.js, mixed.events.js, in the method `updateScaling(....)`, the first line currently is `var currentList = context.cloneArray(ui.contrasts.value(), []);` but my feeling is that it should be `var currentList = context.cloneArray(ui.scaling.value(), []);` (edited)

This occurs in all three files.

The effect in the use of GAMlj is the following:

If you change the scaling from the default 'centered' to something else, and then click the options away, when you return to the analysis it will rerun using the default scaling (even though the UI still specify's the new scaling)

**Comment by mcfanda** [comment]
Checked and corrected. It will be in version 1.0.0

**Comment by gynt** [comment]
Off-topic: this issue arose right after the 3-day course of @mcfanda which he gave yesterday for PhDs and in which he strongly advocated to use jamovi. Many of us are a fan of this software now and see its potential.

**Comment by mcfanda** [comment]
strongly but gently :-)

**Comment by gynt** [comment]
I am now having similar issues when making a General Linear Model.
When selecting two components in the Model Builder and adding their interaction terms (by pressing the arrow), the action of clicking on a gray area in the results overview (losing focus) and then clicking on the results produced by the model (regaining focus), makes the interaction term go away again.

**Comment by dropmann** [comment]
So in regard to the issue with the model builder, if you remove the following code block 
```
    for (let i = 0; i < termsList.length; i++) {
        if (termsList[i].length > 1 && containsCovariate(termsList[i], covariatesList)) {
            termsList.splice(i, 1);
            i -= 1;
            termsChanged = true;
        }
    }
```
from the following files it should solve the issue.
glm.events.js
gzlm.events.js
mixed.events.js

From what i can see this issue will happen in glm, gzlm and mixed analyses.

**Comment by mcfanda** [comment]
It works!! thanks a lot
