### ISSUE TITLE
Error: name space 'rlang' 0.1.1 is already loaded, but> = 0.1.2 is required

### ISSUE THREAD

**Issue by MAgojam** [mcfanda/gamlj#40]
Hi Marcello,
OS: Win7 Pro Ita; jamovi 0.9.0.5; GAMLj 0.9.8.
With "Mixed Models: Repeated measure designs", the inclusion of a component for Random Effects produces the following error (see screenshot):
**name space 'rlang' 0.1.1 is already loaded, but> = 0.1.2 is required**

![screenshot](https://user-images.githubusercontent.com/36552289/40318565-49969cda-5d25-11e8-9588-ef7818c66b0b.png)

Thank you for your time.

Cheers,
Maurizio

**Comment by mcfanda** [comment]
Yes, there is a mismatch between the R version gamlj was built for and the
latest version of jamovi R version. We are solving this presently

Il lun 21 mag 2018, 18:34 MAgojam <notifications@github.com> ha scritto:

**Comment by mcfanda** [comment]
Does the error occur every time you use gamlj? Does it work when the mixed model is the first analysis you run after opening jamovi?

**Comment by MAgojam** [comment]
I have verified and the error only occurs if mixed model is the first analysis performed after the opening of jamovi.

Greetings,
Maurizio

**Comment by mcfanda** [comment]
thanks, it's a version mismatch with the underlying R packages. We'll fix it in version 1.0.0
