### ISSUE TITLE
Variable names with spaces in them

### ISSUE THREAD

**Issue by ontogenerator** [mcfanda/gamlj#41]
Hello Marcello,

thank you for the great package. It was quite useful for me when teaching students about data analysis and statistics.
We discovered the following issue:
Trying to plot the results of a glm with a variable which has a space character in the name leads to the following error message:
**'cannot coerce class "try-error" to a data.frame'**.

Cheers,

Vladislav

**Comment by mcfanda** [comment]
Yes, variable names with space create errors in the current version. Next version (which will come up in about a month) will fix that, sorry

**Comment by ontogenerator** [comment]
Thanks! Keep up the good work!
