### ISSUE TITLE
Reopening model, fixed effects, factor and covariate specs revert to default

### ISSUE THREAD

**Issue by bknakker** [mcfanda/gamlj#42]
Hi,

As I state in the title: whenever I re-open a model, the fixed effects, covariate scaling and factor coding revert to default. In my case, I want to include a covariate in the fixed effects, and it disappears every time I load the analysis, and the covscaling factorcoding specs also get back to their defaults.

Best,
Balázs

**Comment by mcfanda** [comment]
thanks, it has been fixed in the next version (1.0.0) coming out in a few weeks
