### ISSUE TITLE
Separate fixed effect plots contain all points regardless of splitting factor level

### ISSUE THREAD

**Issue by bknakker** [mcfanda/gamlj#43]
Hi,

For Mixed Models, at the Fixed Effects Plots panel,  if I tick Obseved scores and specify a factor for "separate plots", all observations appear on all of the plots.

Best,
Balázs

**Comment by mcfanda** [comment]
thanks, it is fixed in version 1.0.0 (almost ready to be released)

**Comment by mcfanda** [comment]
solved in version 1.0.0. It now select only the observed scores in the "separate plots" level. The only exception is when the "separate plots" is a continuous variable, all observed scores are plotted in each plot.
