### ISSUE TITLE
Simple effects dialogue box does not working

### ISSUE THREAD

**Issue by hyunsooseol** [mcfanda/gamlj#58]
Hello?

When I tried to run 'simple effects' in the dialogue box, the following message appears and does not working..

![image1](https://user-images.githubusercontent.com/37318620/49065291-e5252880-f260-11e8-9aa7-4bd270b07d79.jpg)

Furthermore, plot option also produces the following error message.
![i2](https://user-images.githubusercontent.com/37318620/49065383-3a613a00-f261-11e8-834b-afa0ca61b8fe.jpg)

I am using jamovi version(0.9.510) and GLMLj(ver.1.0.3)

**Comment by psychbruce** [comment]
Many classmates and I just meet the same problem. It seems that the "Simple Effects" dialog box in new version of GAMLj (about >= version 1.0.0 ?) has some unknown bugs. Indeed, the old version (0.9.7) works well. May @mcfanda please fix the bug? I believe not a few people would meet this problem. Thanks very much!

**Comment by mcfanda** [comment]
Hi
it seems a problem with the specific operative system because I cannot reproduce the problem in linux. May I ask which operative system you have, which jamovi version and which gamlj version?

**Comment by hyunsooseol** [comment]
Hi

I am using win 10, jamovi version(0.9.510) and GLMLj(ver.1.0.3).  
Ironically, by using syntax mode in R editor in jamovi, the simple effects and simple plot produce the results well, and then the dialogue box in jamovi works well.

**Comment by psychbruce** [comment]
Hi, I'm also using win 10, jamovi version 0.9.5.2. This problem has already existed in October 4, when I downloaded GAMLj version 1.0.1 (and version 1.0.0 also had this problem, whereas 0.9.7 did not).

**Comment by mcfanda** [comment]
Version 1.0.4 should fix the issue

**Comment by Gootjes** [comment]
Confirmed working in version 1.0.4 (git) and Jamovi 0.9.5.10
