### ISSUE TITLE
Simple effects estimates differ for dummy and simple contrast types

### ISSUE THREAD

**Issue by Gootjes** [mcfanda/gamlj#59]
Dear Marcello,

Simple effects were working fine in the previous version of GAMLJ, however, currently, the estimates are based off the wrong values. It compares the estimates against 0, instead of against the value of the control condition (my reference group), see image for my context.

I hope this is an easy fix

![image](https://user-images.githubusercontent.com/37846483/49075650-7bdcef80-f237-11e8-9521-b929788ba900.png)

**Comment by Gootjes** [comment]
I figured this issue does not refer to the latest Jamovi version, but to the stable one. #58 is what I experience using the latest Jamovi.

**Comment by Gootjes** [comment]
Okay, to avoid any confusion, I now use the gamlj package in R (version 1.0.3)! (cutting out Jamovi as middleman).

I figured out what the origin of the issue is. I assumed the contrast types "dummy" and "simple" to be the same thing. And they also look the same throughout the analysis. However, they are not.

When computing simple effects, when "dummy" contrasts are used, the estimates include the intercept (making them very large and always significant when the DV has a intercept around 4.00). (see analysis1)

When "simple" contrasts are used, the estimates reflect the difference in the DV. (see analysis2)

**Syntax**
```
data <- as.data.frame(matrix(data = c(1,3,1,
                1,4,2,
                1,5,3,
                1,3,4,
                1,2,5,
                1,3,6,
                1,4,7,
                1,3,7,
                1,5,6,
                1,3,5,
                0,6,4,
                0,3,3,
                0,2,2,
                0,4,1,
                0,3,1,
                0,2,2,
                0,1,3,
                0,2,4,
                0,3,5,
                0,4,6), ncol=3, byrow = T))

analysis1 <- gamlj::gamljGLM(
    data = data,
    dep = "V3",
    factors = "V1",
    covs = "V2",
    modelTerms = list(
        "V2",
        "V1",
        c("V1", "V2")),
    contrasts = list(
        list(
            var="V1",
            type="dummy")), #This is the offending line, change this to "simple" and you get different results.
    simpleVariable = "V1",
    simpleModerator = "V2",
    scaling = list(
        list(
            var="V2",
            type="centered")))

analysis2 <- gamlj::gamljGLM(
    data = data,
    dep = "V3",
    factors = "V1",
    covs = "V2",
    modelTerms = list(
        "V2",
        "V1",
        c("V1", "V2")),
    contrasts = list(
        list(
            var="V1",
            type="simple")), #This is the offending line, change this to "simple" and you get different results.
    simpleVariable = "V1",
    simpleModerator = "V2",
    scaling = list(
        list(
            var="V2",
            type="centered")))

print(analysis1$simpleEffects$Params)
print(analysis2$simpleEffects$Params)
```

I was unable to produce this error in Jamovi because I updated GAMLJ in the meantime, and the new GAMLJ and Jamovi gives me the errors as reported in #58

**Comment by mcfanda** [comment]
Hi. As regards the estimates, "dummy" should give the same simple effects than "simple". Thus, this is a bug that I fixed (thanks for spotting it). It will be in version 1.0.4. 
As regards the error #58 , it is a version mismatch with the R packages and occurs only in Windows (I cannot reproduce it in linux). We are investigating it and hopefully solve it for 1.0.4

**Comment by mcfanda** [comment]
The only difference between "simple" and "dummy" are the intercepts, which in simple are the average sample mean (given the other variables), in dummy are the mean for the group scoring 0.

**Comment by Gootjes** [comment]
I am glad to have helped out !

> The only difference between "simple" and "dummy" are the intercepts, which in simple are the average sample mean (given the other variables), in dummy are the mean for the group scoring 0.

Ah right, that makes much sense! Although these terms are (or rather, should be :) ) common statistical knowledge, maybe tooltips shortly explaining how they compare would be nice? I don't know if Jamovi UI supports tooltips.

**Comment by mcfanda** [comment]
Hi, tooltips will be great. In the meantime you can find info in the GAMLj docs here: https://mcfanda.github.io/gamlj_docs/rosetta_contrasts.html. 
And thanks for the help
