### ISSUE TITLE
Plot does not update after adding interaction

### ISSUE THREAD

**Issue by Gootjes** [mcfanda/gamlj#63]
Using the latest version from github (1.0.4), generating a plot (covariate on horizontal axis, factor as separate lines) in GLM analysis works fine. But when an interaction term is added (covariate * factor), the plot does not update.
When I force an update to the plot (by ticking un-ticking observed scores for y axis), an updated correct plot is generated.

This issue also existed in 1.0.3

**Syntax**
```
gamlj::gamljGLM(
    data = data,
    dep = "DV",
    factors = "Condition",
    covs = "moderator",
    modelTerms = list(
        "Condition",
        "moderator",
        c("Condition", "moderator")),
    contrasts = list(
        list(
            var="Condition",
            type="dummy")),
    plotHAxis = "moderator",
    plotSepLines = "Condition",
    scaling = list(
        list(
            var="moderator",
            type="centered")))
```

**Comment by mcfanda** [comment]
great, thanks, I incorporated the bug fix (will be in 1.0.5)
