### ISSUE TITLE
GAMLj uses generic icon

### ISSUE THREAD

**Issue by jdittrich** [mcfanda/gamlj#64]
**Story:** As a user I want to tell apart the different functions of Jamovi easily. 

**Problem:** GAMLj uses the generic icon
![image](https://user-images.githubusercontent.com/3416487/50046571-a76c3080-00a5-11e9-8def-2a247dbcb775.png)

**Possible Solution:** Design an icon for GAMLj

I could take on the task (or peers from [opensourcedesign](https://opensourcedesign.net/)). Do you have any ideas of how an icon for GAMLj might look like? I though of a similar design as the *regression* one. 
![image](https://user-images.githubusercontent.com/3416487/50046577-c1a60e80-00a5-11e9-9715-1b476f88cdc6.png)

**Comment by mcfanda** [comment]
Wow, that's a brilliant idea. What about a stylized version, similar to other icons, of this graph

**Comment by jdittrich** [comment]
Yes, I would give that a try, I also had "regression, but more lines" in mind :-)

**Comment by mcfanda** [comment]
thanks a lot

**Comment by jdittrich** [comment]
I know created this, being close to the "linear model" icon in Jamovi and the diagram you posted:

![image](https://user-images.githubusercontent.com/3416487/50175318-be589000-02fc-11e9-8e65-bc051a113a4a.png)

If that is OK for you, I'd attach a zipped SVg, so you can commit it to the repo.

**Comment by mcfanda** [comment]
that's great. Thank you a lot. I'll mention you in the module desc file

**Comment by jdittrich** [comment]
Here is the SVG (zipped, so I can upload to github)
[GAMLjIcon.zip](https://github.com/mcfanda/gamlj/files/2696167/GAMLjIcon.zip)

**Comment by mcfanda** [comment]
Great, thanks
