### ISSUE TITLE
interaction term does not working

### ISSUE THREAD

**Issue by hyunsooseol** [mcfanda/gamlj#65]
Hi

I am using win 10 and GAMLj(ver. 1.0.4)
When I try to run interaction in Model box, the following error message appears;

![error](https://user-images.githubusercontent.com/37318620/50064777-4ef87880-01f6-11e9-8665-239447370b32.jpg)

Could you check it for me? Thanks in advance.

**Comment by Gootjes** [comment]
Same here, using win 10, jamovi 0.9.5.13, and gamlj 1.0.4.

Running a GLM with one factor and one covariate, DV is continuous

![gamlj](https://user-images.githubusercontent.com/37846483/50076776-de942c00-01e2-11e9-89fe-04fff51e4cfd.png)

**Comment by mcfanda** [comment]
Hi, did you install GAMLj from the jamovi library or from github?

**Comment by hyunsooseol** [comment]
I installed GALj from jamovi library.  and I am also using jamovi(0.9.5.13)

**Comment by mcfanda** [comment]
Yes, 1.0.4 has an issue with  jamovi(0.9.5.13). In a few days 1.0.5 will come out that fixes this issue. If you need 1.0.4 to work, you should downgrade jamovi for a couple of days.

**Comment by mcfanda** [comment]
or install 1.0.5 from github

**Comment by mcfanda** [comment]
version 1.0.5 is out, it should solve the problem

**Comment by Gootjes** [comment]
Confirmed v 1.0.5 to be working on win 10

**Comment by hyunsooseol** [comment]
Thank  you ^^
