### ISSUE TITLE
Fixed effect plots are inconsistent with simple effects test with continuous moderator

### ISSUE THREAD

**Issue by bknakker** [mcfanda/gamlj#72]
Probably the plots are mixed up, I suspect that the mean is the last one and mean+sd is the middle one (according to plot titles they are supposed to be in increasing order)

**Comment by mcfanda** [comment]
Hi, it seems that I cannot replicate the issue. Can you please send me a .omv file with the issue, that will help alot

**Comment by mcfanda** [comment]
I'm in version 1.0.5. Did you see a difference if you select "Labels" or "Valiue + Labels"? I can see a bug when  "Valiue + Labels"

**Comment by mcfanda** [comment]
I've checked with several datasets, it seems that the results are correct. Would you confirm?

**Comment by bknakker** [comment]
Hi,
Sorry, I did not specify the problem really well. Now I replicated this with a dummy dataset. I'm using the mixed model module. The problem occurs when the "Separate plots" variable is used. When this variable had levels 1,2,3 (these were the slopes w.r.t. the variable "Regressor" actually within the groups represented by the variable) the slopes displayed matched the labels. However, when I recoded them to 1->C, 2->A, 3->B, the plots are not displayed correctly (1 is displayed third with label B, 2 is displayed first with label C and 3 is displayed second with label A). 

I've put the sample omv file in my dropbox, you can access it here: https://www.dropbox.com/s/8f3uefx5vm8v2uo/testdata_gamlj_issue_72.omv?dl=1 (I'll delete it when this issue is closed.). The first analysis is the one with the original labels (1,2,3), the second displays the bug with the recoded labels (A,B,C), and the third is just a descriptive stat block demonstrating the mapping between the two.

Currently I tested this on jamovi 0.9.5.16 and GAMLj 1.0.5., but I experienced similar anomalies with 0.9.5.15 and GAMLj 1.0.5.

**Comment by roslinayong** [comment]
Hi, I faced a similar problem as well. Ran a general linear model with two covariates. The results plots seem to be mixed up.

**Comment by mcfanda** [comment]
HI
I can confirm that forthcoming 1.5.0 has fixed the issue. Please notice that due to the many changes introduced in 1.5.0, your ovm file will not work. An aupdate versio is  [here](https://github.com/mcfanda/gamlj/blob/version.1.5.0/uitests/testdata_gamlj_issue_72.omv) . Please let me know if you want it removed from the repository)
