### ISSUE TITLE
How to make this plot in your manual "Mixed Models: Random coefficients regression"

### ISSUE THREAD

**Issue by waurimal** [mcfanda/gamlj#75]
Hi, I have a question.
How to make this plot ?
URL is "https://mcfanda.github.io/gamlj_docs/examples/mixed1/scat2.png"

**Comment by mcfanda** [comment]
Hi, if you are on the latest version, you can do 
![image](https://user-images.githubusercontent.com/5815641/52164597-27049c00-26f4-11e9-99e9-12d21f293878.png)

and get this

![image](https://user-images.githubusercontent.com/5815641/52164606-38e63f00-26f4-11e9-9fc0-3ec15a7a9c30.png)

which is a bit more "publication ready" than the one in the example
