### ISSUE TITLE
Random Component in Mixed model

### ISSUE THREAD

**Issue by hyunsooseol** [mcfanda/gamlj#78]
Hi

Could you provide the results of  the statistical testing(chi-square testing) about Random Component(intercept and slopes) in the Mixed model?

Thanks in advance. ^^

Best Regards

Seol

**Comment by mcfanda** [comment]
It is already available in "Random Effects" tab
![image](https://user-images.githubusercontent.com/5815641/52906292-308c1900-3249-11e9-8c2e-bea76acc85d7.png)
